# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
apply = ["defer"]
# apply = ["source"]

[plugins]

[templates]
defer = '{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}{{ hooks?.post | nl }}'
path = 'path=( "{{ dir }}" $path )'
# fpath = 'fpath=( "{{ dir }}" $fpath )'
fpath_completion = 'fpath=( "{{ dir }}/completions" $fpath )'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]
apply = ["source"]

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.jq-zsh]
github = "reegnz/jq-zsh-plugin"

[plugins.zsh-replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"


[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
