# NOTEBOOK SETTINGS
[notebook]
dir = "~/Documents/notebook/"

[note]
template = "default.md"
exclude = ["archive/**", "_private/**", "projects/**", "journal/**"]
filename = "{{format-date now 'timestamp'}}"

[format.markdown]
link-format = "[[{{filename}}|{{title}}]]"


[lsp.completion]
# Show the note title in the completion pop-up, or fallback on its path if empty.
note-label = "{{title-or-path}}"
# Filter out the completion pop-up using the note title or its path.
note-filter-text = "{{title}} {{path}}"
# Show the note filename without extension as detail.
[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d-%A'}}"
extension = "md"
template = "daily.md"

[group.weekly]
paths = ["journal/weekly"]

[group.weekly.note]
filename = "{{format-date now '%Y-W%U'}}"
extension = "md"
template = "weekly.md"

[tool]
editor = "nvim"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
daily = '~/.dotfiles/scripts/zk/daily.sh'
weekly = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/weekly"'
random = "zk edit --sort random --limit 1"
lint = 'zk list --format \"{{abs-path}}\" --quiet --limit 100 "$@" | xargs textlint --config ~/.config/textlint/.textlintrc.json'
inline = "zk list --quiet --format {{path}} --delimiter , $@"
paths = 'zk list --quiet --format \"{{abs-path}}\" "$@"'
old = "zk list read_inbox --sort created --created-before 'last two weeks'"
save = 'git pull --rebase && git add . && git commit -m "update" && git push'
