# xnoremap(keymapper for linux)
# https://github.com/xremap/xremap
keypress_delay_ms: 20

keymap:
  - name: Emas Like
    application:
      not: [Alacritty, org.wezfurlong.wezterm, com.mitchellh.ghostty]
    remap:
      Ctrl-B: Left
      Ctrl-F: Right
      Ctrl-P: Up
      Ctrl-N: Down
      Ctrl-A: Home
      Ctrl-E: End
      Ctrl-W: CONTROL-BackSpace
  - name: obsidian
    application:
      only: [obsidian]
    remap:
      SUPER-o: CONTROL-o
      SUPER-p: CONTROL-p
  - name: copy paste
    application:
      only: [Alacritty, org.wezfurlong.wezterm, com.mitchellh.ghostty]
    remap:
      SUPER-v: CONTROL-SHIFT-v
  - name: Mac Like SUPER
    application:
      not: [Alacritty, org.wezfurlong.wezterm, NeoVim, com.mitchellh.ghostty]
    remap:
      SUPER-c: CONTROL-c
      SUPER-x: CONTROL-x
      SUPER-v: CONTROL-v
      SUPER-s: CONTROL-s
      SUPER-f: CONTROL-f
      SUPER-z: CONTROL-z
      SUPER-SHIFT-z: CONTROL-SHIFT-z
