# xnoremap(keymapper for linux)
# https://github.com/xremap/xremap
keypress_delay_ms: 20

keymap:
  - name: Emas Like
    application:
      only: [zen-beta]
    remap:
      Ctrl-B: Left
      Ctrl-F: Right
      Ctrl-P: Up
      Ctrl-N: Down
      # Ctrl-A: Home
      Ctrl-E: End
      Ctrl-W: CONTROL-BackSpace
  - name: copy paste
    application:
      only:
        [kitty, Alacritty, org.wezfurlong.wezterm, com.mitchellh.ghostty, code]
    remap:
      SUPER-v: CONTROL-SHIFT-v
      SUPER-c: CONTROL-SHIFT-c
  - name: Mac Like SUPER
    application:
      not:
        [
          kitty,
          Alacritty,
          org.wezfurlong.wezterm,
          NeoVim,
          com.mitchellh.ghostty,
        ]
    remap:
      SUPER-c: CONTROL-c
      SUPER-x: CONTROL-x
      SUPER-v: CONTROL-v
      SUPER-s: CONTROL-s
      SUPER-f: CONTROL-f
      SUPER-a: CONTROL-a
      SUPER-z: CONTROL-z
      SUPER-SHIFT-z: CONTROL-SHIFT-z
