repoPaths:
  :owner/:repo: ~/src/github.com/:owner/:repo # template if you always clone GitHub repos in a consistent location
  tks1197/dotfiles: ~/.dotfiles/
keybindings:
  prs:
    - key: d
      command: |-
        tmux new-window -c {{.RepoPath}} '
          tmux rename-window {{.RepoName}}#{{.PrNumber}} &&
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen origin/$(gh pr status --json baseRefName -q '.currentBranch.baseRefName')...{{.HeadRefName}}"
        '
    - key: C
      command: |-
        tmux new-window -c {{.RepoPath}} '
          tmux rename-window {{.RepoName}}#{{.PrNumber}} &&
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
