[general]
live_config_reload = true
import = [
  # "./themes/catppuccin-frappe.toml",
  # "./themes/catppuccin-macchiato.toml",
  # "./themes/catppuccin-mocha.toml",
  "./themes/nord.toml",
]
[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "None"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.normal]
# family = "JetbrainsMono Nerd Font Mono"
family = "UDEV Gothic 35NF"
style = "Regular"

[font.bold]
family = "UDEV Gothic 35NF"
# family = "JetbrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UDEV Gothic 35NF"
# family = "JetbrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "UDEV Gothic 35NF"
# family = "JetbrainsMono Nerd Font Mono"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
bindings = [{ key = "C", mods = "Control|Shift", chars = "\u0003" }]
