[general]
live_config_reload = true
import = [
  # "./themes/catppuccin-frappe.toml",
  # "./themes/catppuccin-macchiato.toml",
  # "./themes/catppuccin-mocha.toml",
  # "./themes/nord.toml",
]
[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "None"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.normal]
# family = "JetbrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "JetbrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "JetbrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "JetbrainsMono Nerd Font Mono"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Beam"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
bindings = [{ key = "C", mods = "Control|Shift", chars = "\u0003" }]
# name: GYOKURO colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/gyokuro.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#1b1c1d'
# alternate, darker background = '#161617'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1b1c1d'

# Normal colors
[colors.normal]
black = '#767777'
red = '#4F654C'
green = '#6C7355'
yellow = '#5B6078'
blue = '#5E725B'
magenta = '#8B7177'
cyan = '#50616F'
white = '#7B7B7F'

# Bright colors
[colors.bright]
black = '#b08c7d'
red = '#72966c'
green = '#a2ad7b'
yellow = '#868db5'
blue = '#8bab85'
magenta = '#d6a9b3'
cyan = '#748fa6'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#161617'

[[colors.indexed_colors]]
index = 17
color = '#a69e6f'
