# NOTEBOOK SETTINGS
[notebook]
dir = "~/Documents/notebook/"

[note]
template = "default.md"
filename = "{{title}}"
exclude = ["workspaces/journal/**"]
[tool]
editor = "nvim"
[alias]
memo = '~/.local/share/chezmoi/scripts/zk/memo.sh'
note = 'zk new --no-input $ZK_NOTEBOOK_DIR/inbox_literature/ --title "$*"'
random = "zk list --quiet --format full --sort random --limit 1"
search = '~/.local/share/chezmoi/scripts/zk/search.sh "$@"'
# inboxが整理されたらinbox_literatureをフォルダごと削除して、inboxのみとしたい
lint = 'textlint --config ~/.config/textlint/.textlintrc.json "$*"'
todo = '~/.local/share/chezmoi/scripts/zk/todo.sh'
push = "~/.local/share/chezmoi/scripts/zk/push.sh"
pull = "~/.local/share/chezmoi/scripts/zk/pull.sh"
