# NOTEBOOK SETTINGS
[notebook]
dir = "~/Documents/notebook/"

[note]
template = "default.md"
filename = "{{title}}"
exclude = ["archive/**"]

[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.weekly]
paths = ["journal/weekly"]

[group.weekly.note]
filename = "{{sh '~/.local/share/chezmoi/scripts/zk/get_month_of_week.sh'}}"
extension = "md"
template = "weekly.md"

[tool]
editor = "nvim"

[alias]
daily = '~/.local/share/chezmoi/scripts/zk/daily.sh'
weekly = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/weekly"'
note = 'zk new --no-input $ZK_NOTEBOOK_DIR/inbox_literature/ --title "$*"'
random = "zk list --quiet --format full --sort random --limit 1"
lint = 'zk list --format \"{{abs-path}}\" --quiet --limit 100 "$@" | xargs textlint --config ~/.config/textlint/.textlintrc.json'
inline = "zk list --quiet --format {{path}} --delimiter , $@"
paths = "zk list --quiet --format \"'{{path}}'\" --delimiter ' ' $@"
save = 'git add . && git commit -m "$*"'
