# NOTEBOOK SETTINGS
[notebook]
dir = "~/Documents/notebook/"

[note]
template = "default.md"
filename = "{{title}}"
[tool]
editor = "nvim"
[alias]
random = "zk list --quiet --format full --sort random --limit 1"
note = 'zk new --no-input $ZK_NOTEBOOK_DIR/inbox/ --title "$*"'
memo = '~/.local/share/chezmoi/scripts/zk/memo.sh'
todo = '~/.local/share/chezmoi/scripts/zk/todo.sh'
push = "~/.local/share/chezmoi/scripts/zk/push.sh"
pull = "~/.local/share/chezmoi/scripts/zk/pull.sh"
