---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: neovim
    path: "./dictionary/neovim.txt"
    addWords: true
  - name: data_engineering
    path: "./dictionary/data_engineering.txt"
    addWords: true
  - name: forbidden
    path: "./dictionary/forbidden.txt"
    addWords: true
dictionaries:
  - forbidden
  - neovim
  - data_engineering
ignorePaths:
  - "node_modules"
  - "./dictionary/**"
