[tools]
terraform = "1.9.1"
python = "3.12.2"
go = "1.22.2"
usage = "latest"
deno = "2.2.1"
yarn = "latest"
node = "23.7.0"
ruby = "3.3.6"
zig = "0.13"

[settings]
idiomatic_version_file_enable_tools = []
